# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.db.models.deletion
from django.conf import settings
import json_field.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost_center',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('cost_center_name', models.TextField(max_length=20)),
                ('functional_group', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('credit_limit', models.FloatField()),
                ('debit_amount', models.FloatField()),
                ('credit_amount', models.FloatField()),
                ('balance_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('dce', models.CharField(max_length=8, serialize=False, primary_key=True)),
                ('name', models.TextField()),
                ('charging_cc_no', models.CharField(max_length=20)),
                ('position', models.TextField()),
                ('cost_center_no', models.ForeignKey(related_name='cc_eFK', to='WISH.Cost_center')),
            ],
        ),
        migrations.CreateModel(
            name='GARV',
            fields=[
                ('product_to_GARV', json_field.fields.JSONField(default='null', help_text='Enter a valid JSON object')),
                ('garv_date', models.DateField(null=True, blank=True)),
                ('garv_no', models.CharField(max_length=10, serialize=False, primary_key=True)),
                ('date_inspected', models.DateField(null=True, blank=True)),
                ('date_confirmed', models.DateField(null=True, blank=True)),
                ('cc_number', models.ForeignKey(related_name='cc_gFK', blank=True, to='WISH.Cost_center', null=True)),
                ('confirmed_by', models.ForeignKey(related_name='dce_FK5', blank=True, to='WISH.Employee', null=True)),
                ('dce', models.ForeignKey(related_name='d_gFK', blank=True, to='WISH.Employee', null=True)),
                ('inspected_by', models.ForeignKey(related_name='dce_FK4', blank=True, to='WISH.Employee', null=True)),
                ('noted_by', models.ForeignKey(related_name='dce_FK6', blank=True, to='WISH.Employee', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCost_center',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('cost_center_name', models.TextField(max_length=20)),
                ('functional_group', models.CharField(max_length=20)),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical cost_center',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCustomer',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('credit_limit', models.FloatField()),
                ('debit_amount', models.FloatField()),
                ('credit_amount', models.FloatField()),
                ('balance_amount', models.FloatField()),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('dce', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.Employee', null=True)),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical customer',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('dce', models.CharField(max_length=8, db_index=True)),
                ('name', models.TextField()),
                ('charging_cc_no', models.CharField(max_length=20)),
                ('position', models.TextField()),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('cost_center_no', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.Cost_center', null=True)),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical employee',
            },
        ),
        migrations.CreateModel(
            name='HistoricalGARV',
            fields=[
                ('product_to_GARV', json_field.fields.JSONField(default='null', help_text='Enter a valid JSON object')),
                ('garv_date', models.DateField(null=True, blank=True)),
                ('garv_no', models.CharField(max_length=10, db_index=True)),
                ('date_inspected', models.DateField(null=True, blank=True)),
                ('date_confirmed', models.DateField(null=True, blank=True)),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('cc_number', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.Cost_center', null=True)),
                ('confirmed_by', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.Employee', null=True)),
                ('dce', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.Employee', null=True)),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
                ('inspected_by', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.Employee', null=True)),
                ('noted_by', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.Employee', null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical garv',
            },
        ),
        migrations.CreateModel(
            name='HistoricalInventory_stat',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('inv_station_no', models.CharField(max_length=20)),
                ('station_description', models.TextField()),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('cost_center_no', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.Cost_center', null=True)),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical inventory_stat',
            },
        ),
        migrations.CreateModel(
            name='HistoricalIRR',
            fields=[
                ('product', json_field.fields.JSONField(default='null', help_text='Enter a valid JSON object')),
                ('irr_no', models.IntegerField(db_index=True)),
                ('date_recv', models.DateField(null=True, blank=True)),
                ('wo_no', models.CharField(max_length=7, null=True, blank=True)),
                ('wrs_number', models.CharField(max_length=8)),
                ('remark', models.TextField(max_length=30, null=True, blank=True)),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('cost_center_no', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.Cost_center', null=True)),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical irr',
            },
        ),
        migrations.CreateModel(
            name='HistoricalIRR_header',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('reference', models.CharField(max_length=20)),
                ('invoice_number', models.CharField(max_length=20)),
                ('po_number', models.CharField(max_length=20)),
                ('dr_number', models.CharField(max_length=20)),
                ('proc_date', models.DateField()),
                ('approved_date', models.DateField()),
                ('type_n', models.CharField(max_length=20)),
                ('date_dlvrd', models.DateField()),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('dce_approved', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.Employee', null=True)),
                ('dce_custodian', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.Employee', null=True)),
                ('dce_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.Employee', null=True)),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical ir r_header',
            },
        ),
        migrations.CreateModel(
            name='HistoricalMIV',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('wrs_number', models.CharField(max_length=8)),
                ('date_issued', models.DateField()),
                ('doc_date', models.DateField()),
                ('remark', models.TextField(null=True, blank=True)),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical miv',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPAR',
            fields=[
                ('product', json_field.fields.JSONField(default='null', help_text='Enter a valid JSON object')),
                ('par_date', models.DateField()),
                ('par_no', models.CharField(max_length=10, db_index=True)),
                ('amt_cost', models.FloatField(null=True, blank=True)),
                ('remark', models.TextField(null=True, blank=True)),
                ('date_acquired', models.DateField(null=True, blank=True)),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical par',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPending',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('item_name', models.TextField()),
                ('serial_number', models.CharField(max_length=10)),
                ('model', models.TextField()),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical pending',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('nsn', models.CharField(max_length=10)),
                ('slc_number', models.IntegerField()),
                ('product_number', models.CharField(max_length=10)),
                ('generic_name', models.TextField(max_length=25)),
                ('item_name', models.CharField(max_length=10)),
                ('brand', models.TextField(max_length=25)),
                ('part_number', models.CharField(max_length=8)),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField(null=True, blank=True)),
                ('unit_cost', models.FloatField()),
                ('quantity', models.FloatField(default=b'1')),
                ('classification', models.CharField(max_length=30)),
                ('stock', models.CharField(max_length=10)),
                ('block', models.CharField(max_length=10)),
                ('unit_measure', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('average_amount', models.FloatField()),
                ('balance_limit', models.FloatField()),
                ('serial_number', models.CharField(max_length=15)),
                ('model', models.TextField(max_length=25)),
                ('amount', models.FloatField()),
                ('description', models.TextField(max_length=25)),
                ('remark', models.TextField(max_length=25, null=True, blank=True)),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical product',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProduct_to_PAR',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('qty', models.IntegerField()),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical product_to_par',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSupplier',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('supplier_number', models.CharField(max_length=8)),
                ('supplier_name', models.TextField(max_length=20)),
                ('supplier_address', models.TextField(max_length=20)),
                ('telephone_number', models.CharField(max_length=20)),
                ('credit_limit', models.FloatField()),
                ('debit_amount', models.FloatField()),
                ('credit_amount', models.FloatField()),
                ('balance_amount', models.FloatField()),
                ('contact_person', models.TextField(max_length=20)),
                ('remarks', models.TextField(max_length=20)),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical supplier',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTry',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical try',
            },
        ),
        migrations.CreateModel(
            name='Inventory_stat',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('inv_station_no', models.CharField(max_length=20)),
                ('station_description', models.TextField()),
                ('cost_center_no', models.ForeignKey(related_name='cc_iFK', to='WISH.Cost_center')),
            ],
        ),
        migrations.CreateModel(
            name='IRR',
            fields=[
                ('product', json_field.fields.JSONField(default='null', help_text='Enter a valid JSON object')),
                ('irr_no', models.IntegerField(serialize=False, primary_key=True)),
                ('date_recv', models.DateField(null=True, blank=True)),
                ('wo_no', models.CharField(max_length=7, null=True, blank=True)),
                ('wrs_number', models.CharField(max_length=8)),
                ('remark', models.TextField(max_length=30, null=True, blank=True)),
                ('cost_center_no', models.ForeignKey(related_name='ccn_iFK', blank=True, to='WISH.Cost_center', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IRR_header',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('reference', models.CharField(max_length=20)),
                ('invoice_number', models.CharField(max_length=20)),
                ('po_number', models.CharField(max_length=20)),
                ('dr_number', models.CharField(max_length=20)),
                ('proc_date', models.DateField()),
                ('approved_date', models.DateField()),
                ('type_n', models.CharField(max_length=20)),
                ('date_dlvrd', models.DateField()),
                ('dce_approved', models.ForeignKey(related_name='dce3', to='WISH.Employee')),
                ('dce_custodian', models.ForeignKey(related_name='dce1', to='WISH.Employee')),
                ('dce_user', models.ForeignKey(related_name='dce2', to='WISH.Employee')),
                ('inv_station_no', models.ForeignKey(related_name='is_iFK', to='WISH.Inventory_stat')),
            ],
        ),
        migrations.CreateModel(
            name='MIV',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('wrs_number', models.CharField(max_length=8)),
                ('date_issued', models.DateField()),
                ('doc_date', models.DateField()),
                ('remark', models.TextField(null=True, blank=True)),
                ('inv_station_no', models.ForeignKey(related_name='is_mFK', to='WISH.Inventory_stat')),
                ('irr_no', models.ForeignKey(related_name='i_mFK', to='WISH.IRR')),
            ],
        ),
        migrations.CreateModel(
            name='PAR',
            fields=[
                ('product', json_field.fields.JSONField(default='null', help_text='Enter a valid JSON object')),
                ('par_date', models.DateField()),
                ('par_no', models.CharField(max_length=10, serialize=False, primary_key=True)),
                ('amt_cost', models.FloatField(null=True, blank=True)),
                ('remark', models.TextField(null=True, blank=True)),
                ('date_acquired', models.DateField(null=True, blank=True)),
                ('PO_number', models.ForeignKey(related_name='po_pFK', blank=True, to='WISH.IRR_header', null=True)),
                ('approved_by', models.ForeignKey(related_name='dce_FK2', blank=True, to='WISH.Employee', null=True)),
                ('dce', models.ForeignKey(related_name='d_pFK', blank=True, to='WISH.Employee', null=True)),
                ('inv_stat_no', models.ForeignKey(related_name='is_pFK', blank=True, to='WISH.Inventory_stat', null=True)),
                ('issued_by', models.ForeignKey(related_name='dce_FK3', blank=True, to='WISH.Employee', null=True)),
                ('wo_number', models.ForeignKey(related_name='wo_pFK', blank=True, to='WISH.IRR', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('item_name', models.TextField()),
                ('serial_number', models.CharField(max_length=10)),
                ('model', models.TextField()),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('nsn', models.CharField(max_length=10)),
                ('slc_number', models.IntegerField()),
                ('product_number', models.CharField(max_length=10)),
                ('generic_name', models.TextField(max_length=25)),
                ('item_name', models.CharField(max_length=10)),
                ('brand', models.TextField(max_length=25)),
                ('part_number', models.CharField(max_length=8)),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField(null=True, blank=True)),
                ('unit_cost', models.FloatField()),
                ('quantity', models.FloatField(default=b'1')),
                ('classification', models.CharField(max_length=30)),
                ('stock', models.CharField(max_length=10)),
                ('block', models.CharField(max_length=10)),
                ('unit_measure', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('average_amount', models.FloatField()),
                ('balance_limit', models.FloatField()),
                ('serial_number', models.CharField(max_length=15)),
                ('model', models.TextField(max_length=25)),
                ('amount', models.FloatField()),
                ('description', models.TextField(max_length=25)),
                ('remark', models.TextField(max_length=25, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_to_PAR',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('qty', models.IntegerField()),
                ('par_no', models.ForeignKey(related_name='par_ppFK', to='WISH.PAR')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('supplier_number', models.CharField(max_length=8)),
                ('supplier_name', models.TextField(max_length=20)),
                ('supplier_address', models.TextField(max_length=20)),
                ('telephone_number', models.CharField(max_length=20)),
                ('credit_limit', models.FloatField()),
                ('debit_amount', models.FloatField()),
                ('credit_amount', models.FloatField()),
                ('balance_amount', models.FloatField()),
                ('contact_person', models.TextField(max_length=20)),
                ('remarks', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Try',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('text', models.ManyToManyField(to='WISH.PAR')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='purchased_from',
            field=models.ForeignKey(related_name='s_pFK', to='WISH.Supplier'),
        ),
        migrations.AddField(
            model_name='pending',
            name='supplier_number',
            field=models.ForeignKey(related_name='sn_penFK', to='WISH.Supplier'),
        ),
        migrations.AddField(
            model_name='irr_header',
            name='supplier',
            field=models.ForeignKey(related_name='s_iFK', to='WISH.Supplier'),
        ),
        migrations.AddField(
            model_name='irr',
            name='irr_headkey',
            field=models.ForeignKey(related_name='ih_iFK', to='WISH.IRR_header'),
        ),
        migrations.AddField(
            model_name='historicalproduct_to_par',
            name='par_no',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.PAR', null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='purchased_from',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.Supplier', null=True),
        ),
        migrations.AddField(
            model_name='historicalpending',
            name='supplier_number',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.Supplier', null=True),
        ),
        migrations.AddField(
            model_name='historicalpar',
            name='PO_number',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.IRR_header', null=True),
        ),
        migrations.AddField(
            model_name='historicalpar',
            name='approved_by',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.Employee', null=True),
        ),
        migrations.AddField(
            model_name='historicalpar',
            name='dce',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.Employee', null=True),
        ),
        migrations.AddField(
            model_name='historicalpar',
            name='history_user',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='historicalpar',
            name='inv_stat_no',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.Inventory_stat', null=True),
        ),
        migrations.AddField(
            model_name='historicalpar',
            name='issued_by',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.Employee', null=True),
        ),
        migrations.AddField(
            model_name='historicalpar',
            name='wo_number',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.IRR', null=True),
        ),
        migrations.AddField(
            model_name='historicalmiv',
            name='inv_station_no',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.Inventory_stat', null=True),
        ),
        migrations.AddField(
            model_name='historicalmiv',
            name='irr_no',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.IRR', null=True),
        ),
        migrations.AddField(
            model_name='historicalirr_header',
            name='inv_station_no',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.Inventory_stat', null=True),
        ),
        migrations.AddField(
            model_name='historicalirr_header',
            name='supplier',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.Supplier', null=True),
        ),
        migrations.AddField(
            model_name='historicalirr',
            name='irr_headkey',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.IRR_header', null=True),
        ),
        migrations.AddField(
            model_name='historicalgarv',
            name='wo_number',
            field=models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.DO_NOTHING, db_constraint=False, blank=True, to='WISH.IRR_header', null=True),
        ),
        migrations.AddField(
            model_name='garv',
            name='wo_number',
            field=models.ForeignKey(related_name='wo_gFK', blank=True, to='WISH.IRR_header', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='dce',
            field=models.ForeignKey(related_name='d_cFK', to='WISH.Employee'),
        ),
        migrations.AlterUniqueTogether(
            name='pending',
            unique_together=set([('supplier_number', 'serial_number', 'model')]),
        ),
    ]
