# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import audit_log.models.fields
import django_extensions.db.fields
import django.utils.timezone
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost_center',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(max_length=40, null=True, editable=False)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(max_length=40, null=True, editable=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(default=django.utils.timezone.now, verbose_name='created', editable=False, blank=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(default=django.utils.timezone.now, verbose_name='modified', editable=False, blank=True)),
                ('cost_center_name', models.TextField(max_length=20)),
                ('functional_group', models.CharField(max_length=20)),
                ('created_by', audit_log.models.fields.CreatingUserField(related_name='created_wish_cost_center_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(related_name='modified_wish_cost_center_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='modified by')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(max_length=40, null=True, editable=False)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(max_length=40, null=True, editable=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(default=django.utils.timezone.now, verbose_name='created', editable=False, blank=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(default=django.utils.timezone.now, verbose_name='modified', editable=False, blank=True)),
                ('credit_limit', models.FloatField()),
                ('debit_amount', models.FloatField()),
                ('credit_amount', models.FloatField()),
                ('balance_amount', models.FloatField()),
                ('created_by', audit_log.models.fields.CreatingUserField(related_name='created_wish_customer_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(max_length=40, null=True, editable=False)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(max_length=40, null=True, editable=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(default=django.utils.timezone.now, verbose_name='created', editable=False, blank=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(default=django.utils.timezone.now, verbose_name='modified', editable=False, blank=True)),
                ('dce', models.CharField(max_length=8, serialize=False, primary_key=True)),
                ('name', models.TextField()),
                ('charging_cc_no', models.CharField(max_length=20)),
                ('position', models.TextField()),
                ('cost_center_no', models.ForeignKey(to='WISH.Cost_center')),
                ('created_by', audit_log.models.fields.CreatingUserField(related_name='created_wish_employee_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(related_name='modified_wish_employee_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='modified by')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='GARV',
            fields=[
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(max_length=40, null=True, editable=False)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(max_length=40, null=True, editable=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(default=django.utils.timezone.now, verbose_name='created', editable=False, blank=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(default=django.utils.timezone.now, verbose_name='modified', editable=False, blank=True)),
                ('garv_date', models.DateField(null=True, blank=True)),
                ('garv_no', models.CharField(max_length=10, serialize=False, primary_key=True)),
                ('date_inspected', models.DateField(null=True, blank=True)),
                ('date_confirmed', models.DateField(null=True, blank=True)),
                ('cc_number', models.ForeignKey(blank=True, to='WISH.Cost_center', null=True)),
                ('confirmed_by', models.ForeignKey(related_name='dce_FK5', blank=True, to='WISH.Employee', null=True)),
                ('created_by', audit_log.models.fields.CreatingUserField(related_name='created_wish_garv_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by')),
                ('dce', models.ForeignKey(blank=True, to='WISH.Employee', null=True)),
                ('inspected_by', models.ForeignKey(related_name='dce_FK4', blank=True, to='WISH.Employee', null=True)),
                ('modified_by', audit_log.models.fields.LastUserField(related_name='modified_wish_garv_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='modified by')),
                ('noted_by', models.ForeignKey(related_name='dce_FK6', blank=True, to='WISH.Employee', null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Inventory_stat',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('inv_station_no', models.CharField(max_length=20)),
                ('station_description', models.TextField()),
                ('cost_center_no', models.ForeignKey(to='WISH.Cost_center')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(max_length=40, null=True, editable=False)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(max_length=40, null=True, editable=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(default=django.utils.timezone.now, verbose_name='created', editable=False, blank=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(default=django.utils.timezone.now, verbose_name='modified', editable=False, blank=True)),
                ('inv_station_no', models.CharField(max_length=20)),
                ('station_description', models.TextField()),
                ('cost_center_no', models.ForeignKey(to='WISH.Cost_center')),
                ('created_by', audit_log.models.fields.CreatingUserField(related_name='created_wish_inventory_stat_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(related_name='modified_wish_inventory_stat_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='modified by')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='IRR',
            fields=[
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(max_length=40, null=True, editable=False)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(max_length=40, null=True, editable=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(default=django.utils.timezone.now, verbose_name='created', editable=False, blank=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(default=django.utils.timezone.now, verbose_name='modified', editable=False, blank=True)),
                ('irr_no', models.IntegerField(serialize=False, primary_key=True)),
                ('date_recv', models.DateField(null=True, blank=True)),
                ('wo_no', models.CharField(max_length=7, null=True, blank=True)),
                ('remark', models.TextField(max_length=30, null=True, blank=True)),
                ('cost_center_no', models.ForeignKey(blank=True, to='WISH.Cost_center', null=True)),
                ('created_by', audit_log.models.fields.CreatingUserField(related_name='created_wish_irr_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='IRR_header',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(max_length=40, null=True, editable=False)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(max_length=40, null=True, editable=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(default=django.utils.timezone.now, verbose_name='created', editable=False, blank=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(default=django.utils.timezone.now, verbose_name='modified', editable=False, blank=True)),
                ('reference', models.CharField(max_length=20)),
                ('invoice_number', models.CharField(max_length=20)),
                ('po_number', models.CharField(max_length=20)),
                ('dr_number', models.CharField(max_length=20)),
                ('proc_date', models.DateField()),
                ('approved_date', models.DateField()),
                ('type_n', models.CharField(max_length=20)),
                ('date_dlvrd', models.DateField()),
                ('created_by', audit_log.models.fields.CreatingUserField(related_name='created_wish_irr_header_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by')),
                ('dce_approved', models.ForeignKey(related_name='dce3', to='WISH.Employee')),
                ('dce_custodian', models.ForeignKey(related_name='dce1', to='WISH.Employee')),
                ('dce_user', models.ForeignKey(related_name='dce2', to='WISH.Employee')),
                ('inv_station_no', models.ForeignKey(to='WISH.Inventory_stat')),
                ('modified_by', audit_log.models.fields.LastUserField(related_name='modified_wish_irr_header_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='modified by')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='MIV',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(max_length=40, null=True, editable=False)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(max_length=40, null=True, editable=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(default=django.utils.timezone.now, verbose_name='created', editable=False, blank=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(default=django.utils.timezone.now, verbose_name='modified', editable=False, blank=True)),
                ('wrs_number', models.CharField(max_length=8)),
                ('date_issued', models.DateField()),
                ('doc_date', models.DateField()),
                ('remark', models.TextField()),
                ('inv_station_no', models.ForeignKey(to='WISH.Inventory_stat')),
                ('irr_no', models.ForeignKey(to='WISH.IRR')),
               ('created_by', audit_log.models.fields.CreatingUserField(related_name='created_wish_miv_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by')),
                ('inv_station_no', models.ForeignKey(to='WISH.Inventory_stat')),
                ('irr_no', models.ForeignKey(to='WISH.IRR')),
                ('modified_by', audit_log.models.fields.LastUserField(related_name='modified_wish_miv_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='modified by')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='PAR',
            fields=[('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(max_length=40, null=True, editable=False)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(max_length=40, null=True, editable=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(default=django.utils.timezone.now, verbose_name='created', editable=False, blank=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(default=django.utils.timezone.now, verbose_name='modified', editable=False, blank=True)),
                ('par_date', models.DateField()),
                ('par_no', models.CharField(max_length=10, serialize=False, primary_key=True)),
                ('amt_cost', models.FloatField(null=True, blank=True)),
                ('remark', models.TextField(null=True, blank=True)),
                ('date_acquired', models.DateField(null=True, blank=True)),
                ('PO_number', models.ForeignKey(blank=True, to='WISH.IRR_header', null=True)),
                ('approved_by', models.ForeignKey(related_name='dce_FK2', blank=True, to='WISH.Employee', null=True)),
                ('dce', models.ForeignKey(blank=True, to='WISH.Employee', null=True)),
                ('inv_stat_no', models.ForeignKey(blank=True, to='WISH.Inventory_stat', null=True)),
                ('issued_by', models.ForeignKey(related_name='dce_FK3', blank=True, to='WISH.Employee', null=True)),
                ('wo_number', models.ForeignKey(blank=True, to='WISH.IRR', null=True)),
                ('created_by', audit_log.models.fields.CreatingUserField(related_name='created_wish_par_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by')),
                ('dce', models.ForeignKey(blank=True, to='WISH.Employee', null=True)),
                ('inv_stat_no', models.ForeignKey(blank=True, to='WISH.Inventory_stat', null=True)),
                ('issued_by', models.ForeignKey(related_name='dce_FK3', blank=True, to='WISH.Employee', null=True)),
                ('modified_by', audit_log.models.fields.LastUserField(related_name='modified_wish_par_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='modified by')),
                ('wo_number', models.ForeignKey(blank=True, to='WISH.IRR', null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
            ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(max_length=40, null=True, editable=False)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(max_length=40, null=True, editable=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(default=django.utils.timezone.now, verbose_name='created', editable=False, blank=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(default=django.utils.timezone.now, verbose_name='modified', editable=False, blank=True)),
                ('item_name', models.TextField()),
                ('serial_number', models.CharField(max_length=10)),
                ('model', models.TextField()),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('created_by', audit_log.models.fields.CreatingUserField(related_name='created_wish_pending_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(related_name='modified_wish_pending_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='modified by')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(max_length=40, null=True, editable=False)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(max_length=40, null=True, editable=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(default=django.utils.timezone.now, verbose_name='created', editable=False, blank=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(default=django.utils.timezone.now, verbose_name='modified', editable=False, blank=True)),
                ('nsn', models.CharField(max_length=10)),
                ('slc_number', models.IntegerField()),
                ('product_number', models.CharField(max_length=10)),
                ('generic_name', models.TextField()),
                ('item_name', models.CharField(max_length=10)),
                ('brand', models.TextField()),
                ('part_number', models.CharField(max_length=8)),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField(null=True, blank=True)),
                ('unit_cost', models.FloatField()),
                ('quantity', models.FloatField(default=b'1')),
                ('classification', models.CharField(max_length=30)),
                ('stock', models.CharField(max_length=10)),
                ('block', models.CharField(max_length=10)),
                ('unit_measure', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('average_amount', models.FloatField()),
                ('balance_limit', models.FloatField()),
                ('serial_number', models.CharField(max_length=15)),
                ('model', models.TextField()),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('remark', models.TextField()),
                ('created_by', audit_log.models.fields.CreatingUserField(related_name='created_wish_product_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(related_name='modified_wish_product_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='modified by')),
            ],

        ),
        migrations.CreateModel(
            name='Product_to_GARV',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('qty', models.CharField(max_length=20)),
                ('remarks', models.CharField(max_length=20, null=True)),
                ('garv', models.ForeignKey(to='WISH.GARV')),
                ('par_number', models.ForeignKey(to='WISH.PAR')),
            ],
        ),
        migrations.CreateModel(
            name='Product_to_IRR',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('quantity_accepted', models.FloatField()),
                ('quantity_rejected', models.FloatField()),
                ('quantity_balance', models.FloatField()),
                ('irr_no', models.ForeignKey(to='WISH.IRR')),
                ('product', models.ForeignKey(to='WISH.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_to_PAR',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('qty', models.IntegerField()),
                ('par_no', models.ForeignKey(to='WISH.PAR')),
                ('product', models.ForeignKey(to='WISH.Product_to_IRR')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Product_to_GARV',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(max_length=40, null=True, editable=False)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(max_length=40, null=True, editable=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(default=django.utils.timezone.now, verbose_name='created', editable=False, blank=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(default=django.utils.timezone.now, verbose_name='modified', editable=False, blank=True)),
                ('qty', models.CharField(max_length=20)),
                ('remarks', models.CharField(max_length=20, null=True)),
                ('created_by', audit_log.models.fields.CreatingUserField(related_name='created_wish_product_to_garv_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by')),
                ('garv', models.ForeignKey(to='WISH.GARV')),
                ('modified_by', audit_log.models.fields.LastUserField(related_name='modified_wish_product_to_garv_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='modified by')),
                ('par_number', models.ForeignKey(to='WISH.PAR')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Product_to_IRR',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(max_length=40, null=True, editable=False)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(max_length=40, null=True, editable=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(default=django.utils.timezone.now, verbose_name='created', editable=False, blank=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(default=django.utils.timezone.now, verbose_name='modified', editable=False, blank=True)),
                ('quantity_accepted', models.FloatField()),
                ('quantity_rejected', models.FloatField()),
                ('quantity_balance', models.FloatField()),
                ('created_by', audit_log.models.fields.CreatingUserField(related_name='created_wish_product_to_irr_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by')),
                ('irr_no', models.ForeignKey(to='WISH.IRR')),
                ('modified_by', audit_log.models.fields.LastUserField(related_name='modified_wish_product_to_irr_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='modified by')),
                ('product', models.ForeignKey(to='WISH.Product')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Product_to_PAR',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(max_length=40, null=True, editable=False)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(max_length=40, null=True, editable=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(default=django.utils.timezone.now, verbose_name='created', editable=False, blank=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(default=django.utils.timezone.now, verbose_name='modified', editable=False, blank=True)),
                ('qty', models.IntegerField()),
                ('created_by', audit_log.models.fields.CreatingUserField(related_name='created_wish_product_to_par_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(related_name='modified_wish_product_to_par_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='modified by')),
                ('par_no', models.ForeignKey(to='WISH.PAR')),
                ('product', models.ForeignKey(to='WISH.Product_to_IRR')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(max_length=40, null=True, editable=False)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(max_length=40, null=True, editable=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(default=django.utils.timezone.now, verbose_name='created', editable=False, blank=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(default=django.utils.timezone.now, verbose_name='modified', editable=False, blank=True)),
                ('supplier_number', models.CharField(max_length=8)),
                ('supplier_name', models.TextField(max_length=20)),
                ('supplier_address', models.TextField(max_length=20)),
                ('telephone_number', models.CharField(max_length=20)),
                ('credit_limit', models.FloatField()),
                ('debit_amount', models.FloatField()),
                ('credit_amount', models.FloatField()),
                ('balance_amount', models.FloatField()),
                ('contact_person', models.TextField(max_length=20)),
                ('remarks', models.TextField(max_length=20)),
                ('created_by', audit_log.models.fields.CreatingUserField(related_name='created_wish_supplier_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(related_name='modified_wish_supplier_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='modified by')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Try',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(max_length=40, null=True, editable=False)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(max_length=40, null=True, editable=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(default=django.utils.timezone.now, verbose_name='created', editable=False, blank=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(default=django.utils.timezone.now, verbose_name='modified', editable=False, blank=True)),
                ('created_by', audit_log.models.fields.CreatingUserField(related_name='created_wish_try_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(related_name='modified_wish_try_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='modified by')),
                ('text', models.ManyToManyField(to='WISH.PAR')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.AddField(
            model_name='product_to_garv',
            name='product',
            field=models.ForeignKey(to='WISH.Product_to_IRR'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchased_from',
            field=models.ForeignKey(to='WISH.Supplier'),
        ),
        migrations.AddField(
            model_name='pending',
            name='supplier_number',
            field=models.ForeignKey(to='WISH.Supplier'),
        ),
        migrations.AddField(
            model_name='irr_header',
            name='supplier',
            field=models.ForeignKey(to='WISH.Supplier'),
        ),
        migrations.AddField(
            model_name='irr',
            name='irr_headkey',
            field=models.ForeignKey(to='WISH.IRR_header'),
        ),
        migrations.AddField(

            model_name='irr',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(related_name='modified_wish_irr_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='garv',
            name='wo_number',
            field=models.ForeignKey(blank=True, to='WISH.IRR_header', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='dce',
            field=models.ForeignKey(to='WISH.Employee'),

        ),
        migrations.AddField(
            model_name='customer',
            name='modified_by',
            field=audit_log.models.fields.LastUserField(related_name='modified_wish_customer_set', editable=False, to=settings.AUTH_USER_MODEL, null=True, verbose_name='modified by'),
        ),
        migrations.AlterUniqueTogether(
            name='pending',
            unique_together=set([('supplier_number', 'serial_number', 'model')]),
        ),
    ]
