# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WISH', '0003_auto_20150420_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='dce_fk',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='cost_center_no_fk',
        ),
        migrations.AlterUniqueTogether(
            name='garv',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='garv',
            name='asset_code_FK',
        ),
        migrations.RemoveField(
            model_name='garv',
            name='dce_FK',
        ),
        migrations.DeleteModel(
            name='GARV',
        ),
        migrations.RemoveField(
            model_name='inventory_stat',
            name='cost_center_no_fk',
        ),
        migrations.RemoveField(
            model_name='irr',
            name='asset_code_fk',
        ),
        migrations.RemoveField(
            model_name='irr',
            name='cost_center_no_fk',
        ),
        migrations.RemoveField(
            model_name='irr',
            name='irr_no_fk',
        ),
        migrations.DeleteModel(
            name='IRR',
        ),
        migrations.RemoveField(
            model_name='irr_header',
            name='dce_custodian',
        ),
        migrations.RemoveField(
            model_name='irr_header',
            name='dce_user',
        ),
        migrations.RemoveField(
            model_name='irr_header',
            name='inv_station_no',
        ),
        migrations.RemoveField(
            model_name='irr_header',
            name='supl_fk',
        ),
        migrations.RemoveField(
            model_name='miv',
            name='asset_code_fk',
        ),
        migrations.RemoveField(
            model_name='miv',
            name='cost_center_no_fk',
        ),
        migrations.RemoveField(
            model_name='miv',
            name='dce_custodian_fk',
        ),
        migrations.RemoveField(
            model_name='miv',
            name='dce_user_fk',
        ),
        migrations.RemoveField(
            model_name='miv',
            name='inv_station_no_fk',
        ),
        migrations.RemoveField(
            model_name='miv',
            name='irr_no_fk',
        ),
        migrations.DeleteModel(
            name='MIV',
        ),
        migrations.AlterUniqueTogether(
            name='par',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='par',
            name='PO_num',
        ),
        migrations.DeleteModel(
            name='IRR_header',
        ),
        migrations.RemoveField(
            model_name='par',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='par',
            name='asset_code_FK',
        ),
        migrations.RemoveField(
            model_name='par',
            name='dce_FK',
        ),
        migrations.RemoveField(
            model_name='par',
            name='inv_stat_no',
        ),
        migrations.RemoveField(
            model_name='par',
            name='issued_by',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='PAR',
        ),
        migrations.AlterUniqueTogether(
            name='pending',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pending',
            name='supplier_num',
        ),
        migrations.DeleteModel(
            name='Pending',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_center_no_fk',
        ),
        migrations.DeleteModel(
            name='Cost_center',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inv_station_no_fk',
        ),
        migrations.DeleteModel(
            name='Inventory_stat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchased_from',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
