# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WISH', '0005_miv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='balance_amt',
            new_name='balance_amount',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='credit_amt',
            new_name='credit_amount',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='dce_fk',
            new_name='dce',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='debit_amt',
            new_name='debit_amount',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='cost_center_no_fk',
            new_name='cost_center_no',
        ),
        migrations.RenameField(
            model_name='garv',
            old_name='asset_code_FK',
            new_name='asset_code',
        ),
        migrations.RenameField(
            model_name='garv',
            old_name='cc_num',
            new_name='cc_number',
        ),
        migrations.RenameField(
            model_name='garv',
            old_name='dce_FK',
            new_name='dce',
        ),
        migrations.RenameField(
            model_name='garv',
            old_name='par_num',
            new_name='par_number',
        ),
        migrations.RenameField(
            model_name='inventory_stat',
            old_name='cost_center_no_fk',
            new_name='cost_center_no',
        ),
        migrations.RenameField(
            model_name='irr',
            old_name='asset_code_fk',
            new_name='asset_code',
        ),
        migrations.RenameField(
            model_name='irr',
            old_name='cost_center_no_fk',
            new_name='cost_center_no',
        ),
        migrations.RenameField(
            model_name='irr',
            old_name='irr_no_fk',
            new_name='irr_no',
        ),
        migrations.RenameField(
            model_name='irr_header',
            old_name='dr_num',
            new_name='dr_number',
        ),
        migrations.RenameField(
            model_name='irr_header',
            old_name='invoice_num',
            new_name='invoice_number',
        ),
        migrations.RenameField(
            model_name='irr_header',
            old_name='po_num',
            new_name='po_number',
        ),
        migrations.RenameField(
            model_name='irr_header',
            old_name='supl_fk',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='miv',
            old_name='asset_code_fk',
            new_name='asset_code',
        ),
        migrations.RenameField(
            model_name='miv',
            old_name='cost_center_no_fk',
            new_name='cost_center_no',
        ),
        migrations.RenameField(
            model_name='miv',
            old_name='inv_station_no_fk',
            new_name='inv_station_no',
        ),
        migrations.RenameField(
            model_name='miv',
            old_name='irr_no_fk',
            new_name='irr_no',
        ),
        migrations.RenameField(
            model_name='miv',
            old_name='wrs_num',
            new_name='wrs_number',
        ),
        migrations.RenameField(
            model_name='par',
            old_name='PO_num',
            new_name='PO_number',
        ),
        migrations.RenameField(
            model_name='par',
            old_name='asset_code_FK',
            new_name='asset_code',
        ),
        migrations.RenameField(
            model_name='par',
            old_name='dce_FK',
            new_name='dce',
        ),
        migrations.RenameField(
            model_name='par',
            old_name='wo_num',
            new_name='wo_number',
        ),
        migrations.RenameField(
            model_name='pending',
            old_name='supplier_num',
            new_name='supplier_number',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='average_amt',
            new_name='average_amount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='class_n',
            new_name='classification',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cost_center_no_fk',
            new_name='cost_center_no',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='inv_station_no_fk',
            new_name='inv_station_no',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='part_num',
            new_name='part_number',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pr_num',
            new_name='product_number',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='slc_num',
            new_name='slc_number',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='balance_amt',
            new_name='balance_amount',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='credit_amt',
            new_name='credit_amount',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='debit_amt',
            new_name='debit_amount',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_num',
            new_name='supplier_number',
        ),
        migrations.RemoveField(
            model_name='garv',
            name='wo_num',
        ),
        migrations.RemoveField(
            model_name='irr_header',
            name='irr_headkey',
        ),
        migrations.AddField(
            model_name='garv',
            name='wo_number',
            field=models.ForeignKey(default=1, to='WISH.IRR_header'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cost_center',
            name='cost_center_name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cost_center',
            name='functional_group',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='garv',
            name='garv_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='garv',
            name='qty',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='garv',
            name='remarks',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='irr_header',
            name='remark',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='par',
            name='par_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pending',
            name='serial_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='block',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=b'1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='serial_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_measure',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='remarks',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_address',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='garv',
            unique_together=set([('dce', 'asset_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='par',
            unique_together=set([('dce', 'asset_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='pending',
            unique_together=set([('supplier_number', 'serial_number', 'model')]),
        ),
    ]
