from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^wrs_form/(?P<pk>[0-9]+)/$', views.wrs_form),
    url(r'^$', views.index),
    url(r'^Aboutus/$', views.aboutus),
    url(r'^product/new/$', views.product_new, name='product_new'),
    url(r'^par/(?P<inv>[0-9]+)/$', views.par),
    url(r'^par_f/$', views.par_f),
    url(r'^irr_entry/$', views.irr_entry, name='irr_entry'),
    url(r'^(?P<msg>\w+)/irr_entry/$', views.irr_entry, name='irr_entry'),
    url(r'^miv_entry/$', views.miv_entry, name='miv_entry'),
    url(r'^miv_entry_S/(?P<pk>[0-9]+)/$', views.miv_entry_S),
    url(r'^par_form/(?P<pk>[0-9]+)/$', views.par_form),
    url(r'^product_form/(?P<pk>[0-9]+)/$', views.product_form),
    url(r'^inv_stat_form/(?P<pk>[0-9]+)/$', views.inv_stat_form),
    url(r'^cost_center_form/(?P<pk>[0-9]+)/$', views.cost_center_form),
    url(r'^supplier_form/(?P<pk>[0-9]+)/$', views.supplier_form),
    url(r'^employee_form/(?P<dce>[0-9]+)/$', views.employee_form),
    url(r'^product_details/(?P<pk>[0-9]+)/$', views.product_details),
    url(r'^inv_stat_details/(?P<pk>[0-9]+)/$', views.inv_stat_details),
    url(r'^inv_stat_del/(?P<pk>[0-9]+)/$', views.inv_stat_del),
    url(r'^cost_center_del/(?P<pk>[0-9]+)/$', views.cost_center_del),
    url(r'^supplier_del/(?P<pk>[0-9]+)/$', views.supplier_del),
    url(r'^employee_del/(?P<pk>[0-9]+)/$', views.employee_del),
    url(r'^cost_center_details/(?P<pk>[0-9]+)/$', views.cost_center_details),
    url(r'^supplier_details/(?P<pk>[0-9]+)/$', views.supplier_details),
    url(r'^employee_details/(?P<dce>[0-9]+)/$', views.employee_details),
    url(r'^garv_entry_f/$', views.garv_entry_f),
    url(r'^product_to_garv/(?P<pk>[0-9]+)/$', views.product_to_garv),
    url(r'^garv_form/(?P<pk>[0-9]+)/$', views.garv_form),
    url(r'^wrs_entry/$', views.wrs_entry),
    url(r'^product_to_irr/(?P<pk>[0-9]+)/(?P<inv>[0-9]+)/$', views.product_to_irr),
    url(r'^irr_form/(?P<pk>[0-9]+)/$', views.irr_form),
    url(r'^miv_form/(?P<pk>[0-9]+)/$', views.miv_form),
    url(r'^inv_stat/$', views.inv_stat),
    url(r'^cost_center/$', views.cost_center),
    url(r'^supplier/$', views.supplier),
    url(r'^employee/$', views.employee),
    url(r'^add_cost_center/$', views.add_cost_center, name='add_cost_center'),
    url(r'^file_reports/$', views.file_report),
    url(r'^irr_reports/$', views.irr_reports),
    url(r'^miv_reports/$', views.miv_reports),
    url(r'^wrs_reports/$', views.wrs_reports),
    url(r'^par_reports/$', views.par_reports),
    url(r'^garv_reports/$', views.garv_reports),
    url(r'^product_reports/$', views.product_reports),
    url(r'^file_entry/$', views.file_entry),
    url(r'^libraries/$', views.libraries),
    url(r'^stat_lib/$', views.stat_lib, name='stat_lib'),
    url(r'^sup_lib/$', views.sup_lib, name='sup_lib'),
    url(r'^employee_lib/$', views.employee_lib, name='employee_lib'),
]
